GET http://localhost:5238/games

###

GET http://localhost:5238/games/3

###
POST http://localhost:5238/games
Content-Type: application/json

{
  "name": "Final Fantasy XIV",
  "genreId": 2,
  "price": 49.99,
  "releaseDate": "2010-11-18"
}

###
PUT  http://localhost:5238/games/3
Content-Type: application/json

{
    "name": "Witcher 3 Blood and Wine",
    "genreId": "1",
    "price": 5.99,
    "releaseDate": "2015-07-20"
}

### 
DELETE http://localhost:5238/games/4